
modLoader="kotlinforforge"
loaderVersion="[1,)"
license="GNU GPLv3"
[[mods]]
modId="enchantnote"
version="0.1"
displayName="Enchanting Secretaire"
authors="qianzha"
description='''
Provide a notebook to recording enchantments.
将成堆的附魔书记录于一本厚重笔记。
'''
[[dependencies.enchantnote]]
    modId="forge" 
    mandatory=true 
    versionRange="[36,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.enchantnote]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
